name: Platform macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: macOS Latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --rerun-failed --output-on-failure
