name: Platform macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: macOS Latest
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: |
          cd build
          ctest --rerun-failed --output-on-failure
